import fs from 'node:fs'
import path from 'node:path'

export type AudioSource = { voice: string; url: string }

const AUDIO_DIR = path.join(process.cwd(), 'public', 'audio')

// Short descriptions of Gemini voices, shown in the picker. Unknown voices just show their name.
export const voiceHints: Record<string, string> = {
  Kore: 'Firm',
  Puck: 'Upbeat',
  Zephyr: 'Bright',
  Charon: 'Informative',
  Fenrir: 'Excitable',
  Leda: 'Youthful',
  Aoede: 'Breezy',
}

/** Audio files generated by `npm run audio` for one term, one entry per voice (MP3, or WAV if ffmpeg was missing). */
export function getAudioSources(id: string): AudioSource[] {
  if (!fs.existsSync(AUDIO_DIR)) return []
  const sources: AudioSource[] = []
  for (const d of fs.readdirSync(AUDIO_DIR, { withFileTypes: true })) {
    if (!d.isDirectory()) continue
    const ext = ['mp3', 'wav'].find((e) => fs.existsSync(path.join(AUDIO_DIR, d.name, `${id}.${e}`)))
    if (ext) sources.push({ voice: d.name, url: `/audio/${d.name}/${id}.${ext}` })
  }
  return sources.sort((a, b) => a.voice.localeCompare(b.voice))
}
