// AI quality review of the glossary content (Arabic + English), using the Gemma bulk tier of the model pool.
// It never edits content: it writes a private report (docs/qa-report-<date>.md and .json) for a human to review.
//
//   npm run qa                         review every term
//   npm run qa -- --only rag,jwt       just these ids
//   npm run qa -- --limit 10           first 10 terms (smoke test)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { generate, mapPool } from './lib/ai-pool.mjs'

const webDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const contentDir = path.join(webDir, '..', 'content')
const docsDir = path.join(webDir, '..', 'docs')

const args = process.argv.slice(2)
const flag = (n) => {
  const i = args.indexOf(`--${n}`)
  return i === -1 ? undefined : args[i + 1]
}
const only = flag('only') ? new Set(flag('only').split(',')) : null
const limit = flag('limit') ? Number(flag('limit')) : Infinity

const terms = []
for (const category of fs.readdirSync(path.join(contentDir, 'en'))) {
  for (const file of fs.readdirSync(path.join(contentDir, 'en', category))) {
    const id = file.replace(/\.md$/, '')
    if (only && !only.has(id)) continue
    terms.push({
      id,
      category,
      en: fs.readFileSync(path.join(contentDir, 'en', category, file), 'utf8'),
      ar: fs.readFileSync(path.join(contentDir, 'ar', category, file), 'utf8'),
    })
  }
}
const batch = terms.slice(0, limit)

const SYSTEM = `You are a strict editor for QamoosTech, a bilingual (Arabic/English) glossary that teaches Arabic-speaking software engineers the English words used at work.
Review ONE term, given as two files: the English file and the Arabic file.
Check ONLY these things:
1. ARABIC STYLE: must be simple Modern Standard Arabic (not Egyptian or any dialect), natural and clear (not word-for-word machine translation), grammatically correct. Technical English terms may stay in English.
2. ARABIC TERM: the Arabic equivalent in "translation" and in the text must be a term engineers actually use, not an awkward invention.
3. CONSISTENCY: the Arabic and English files must say the same thing; every Arabic example translation must match its English sentence.
4. ACCURACY: the definition, context and "common mistake" must be technically correct and not misleading.
5. PRIVACY: examples must be generic. Flag any real company, client, person, product-specific number or personal data.
6. PRONUNCIATION: the English respelling and the Arabic transliteration should plausibly match how the term is said.
Do NOT comment on formatting, front matter, headings, or minor taste. Only report real problems.
Answer with JSON only, no other text, in exactly this shape:
{"issues":[{"severity":"high|medium|low","lang":"ar|en","field":"definition|context|examples|mistake|translation|pronunciation|other","problem":"short explanation","suggestion":"exact replacement text or fix"}]}
Use {"issues":[]} when the term is fine. high = wrong or misleading; medium = clearly awkward or inconsistent; low = small improvement.`

const validate = (d) => {
  if (!d || !Array.isArray(d.issues)) throw new Error('bad shape')
  for (const i of d.issues) if (!['high', 'medium', 'low'].includes(i.severity) || !i.problem) throw new Error('bad issue')
}

console.log(`Reviewing ${batch.length} term(s) with the bulk tier...`)
let done = 0
const results = await mapPool(
  batch,
  async (t) => {
    try {
      const r = await generate({
        tiers: ['bulk', 'draft'],
        system: SYSTEM,
        prompt: `TERM ID: ${t.id}\n\n=== ENGLISH FILE ===\n${t.en}\n\n=== ARABIC FILE ===\n${t.ar}`,
        json: true,
        validate,
        temperature: 0.1,
        maxOutputTokens: 2048,
      })
      process.stdout.write(`\r${++done}/${batch.length} `)
      return { id: t.id, category: t.category, model: r.model, issues: r.data.issues }
    } catch (e) {
      process.stdout.write(`\r${++done}/${batch.length} `)
      return { id: t.id, category: t.category, error: e.message, issues: [] }
    }
  },
  6,
)
console.log()

const order = { high: 0, medium: 1, low: 2 }
const flat = results.flatMap((r) => r.issues.map((i) => ({ id: r.id, category: r.category, model: r.model, ...i })))
flat.sort((a, b) => order[a.severity] - order[b.severity] || a.id.localeCompare(b.id))
const failed = results.filter((r) => r.error)
const count = (s) => flat.filter((i) => i.severity === s).length
const date = new Date().toISOString().slice(0, 10)

let md = `# Content QA report ${date}\n\nGenerated by \`npm run qa\` (Gemma bulk tier). **Suggestions only: review each one before changing a file.**\n\n`
md += `- Terms reviewed: ${batch.length - failed.length} of ${batch.length}\n- Issues: **${count('high')} high**, ${count('medium')} medium, ${count('low')} low\n- Terms with no issues: ${results.filter((r) => !r.error && r.issues.length === 0).length}\n`
if (failed.length) md += `- Could not review: ${failed.map((f) => f.id).join(', ')}\n`
for (const sev of ['high', 'medium', 'low']) {
  const list = flat.filter((i) => i.severity === sev)
  if (!list.length) continue
  md += `\n## ${sev.toUpperCase()} (${list.length})\n\n`
  for (const i of list) {
    md += `### ${i.id} · ${i.lang} · ${i.field}\n- File: \`content/${i.lang}/${i.category}/${i.id}.md\`\n- Problem: ${i.problem}\n- Suggestion: ${i.suggestion || '-'}\n\n`
  }
}
fs.mkdirSync(docsDir, { recursive: true })
fs.writeFileSync(path.join(docsDir, `qa-report-${date}.md`), md)
fs.writeFileSync(path.join(docsDir, `qa-report-${date}.json`), JSON.stringify({ date, results }, null, 2))
console.log(`Done. ${count('high')} high, ${count('medium')} medium, ${count('low')} low. Report: docs/qa-report-${date}.md`)
