'use client'

import { useEffect, useRef, useState } from 'react'

type Source = { voice: string; url: string; label: string }

const BROWSER = 'browser'

// Plays recorded AI voices (generated by `npm run audio`) when they exist for this term,
// with a voice picker; falls back to the browser's built-in speech voice.
export function Speak({ text, label, sources, browserLabel }: { text: string; label: string; sources: Source[]; browserLabel: string }) {
  const [speechOk, setSpeechOk] = useState(false)
  const [playing, setPlaying] = useState(false)
  const [voice, setVoice] = useState(sources[0]?.voice ?? BROWSER)
  const audioRef = useRef<HTMLAudioElement | null>(null)

  useEffect(() => {
    setSpeechOk('speechSynthesis' in window)
    try {
      const saved = localStorage.getItem('voice')
      if (saved && (saved === BROWSER || sources.some((s) => s.voice === saved))) setVoice(saved)
    } catch {}
  }, [sources])

  useEffect(() => () => { audioRef.current?.pause() }, [])

  const options = [...sources.map((s) => ({ id: s.voice, label: s.label })), ...(speechOk ? [{ id: BROWSER, label: browserLabel }] : [])]
  if (options.length === 0) return null
  const current = options.some((o) => o.id === voice) ? voice : options[0].id

  function play() {
    audioRef.current?.pause()
    if (typeof speechSynthesis !== 'undefined') speechSynthesis.cancel()
    const src = sources.find((s) => s.voice === current)
    if (src) {
      const a = new Audio(src.url)
      audioRef.current = a
      a.onplay = () => setPlaying(true)
      a.onended = a.onpause = a.onerror = () => setPlaying(false)
      void a.play()
    } else {
      const u = new SpeechSynthesisUtterance(text)
      u.lang = 'en-US'
      u.rate = 0.85
      u.onstart = () => setPlaying(true)
      u.onend = u.onerror = () => setPlaying(false)
      speechSynthesis.speak(u)
    }
  }

  function choose(id: string) {
    setVoice(id)
    try { localStorage.setItem('voice', id) } catch {}
  }

  return (
    <span className="speak-group">
      <button type="button" className={`speak${playing ? ' speak--on' : ''}`} onClick={play} aria-label={`${label}: ${text}`}>
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M11 5 6 9H2v6h4l5 4V5Z" />
          <path d="M15.5 8.5a5 5 0 0 1 0 7M18.5 5.5a9 9 0 0 1 0 13" />
        </svg>
        {label}
      </button>
      {options.length > 1 && (
        <select className="voice-select" value={current} onChange={(e) => choose(e.target.value)} aria-label="Voice" dir="ltr">
          {options.map((o) => (
            <option key={o.id} value={o.id}>{o.label}</option>
          ))}
        </select>
      )}
    </span>
  )
}
